Adjust debian package generation back to svn.

diff --git a/scripts/debian-prep b/scripts/debian-prep
--- a/scripts/debian-prep
+++ b/scripts/debian-prep
@@ -1,20 +1,24 @@
 #!/bin/sh
 # this script must be run from yade's top-level directory!
 #
-# svn used to be used:
-# REVISION="svn$( svn info | egrep '^Revision:' | cut -f2 -d' ')"
-#
-# bzr used:
-# REVISION="bzr$( bzr version-info | egrep '^revno:' | cut -f2 -d' ')"
-#
 # if there is file RELEASE, it will be the version number ($REVISION) and SNAPSHOT will be empty.
+#
+# Othervwise svn or bzr versioning information will be used.
+#
+# Errors out if RELEASE or .svn or .bzr don't exist.
 #
 if [ -f RELEASE ]; then
 	REVISION=`cat RELEASE`
 	SNAPSHOT=""
-else
+elif [ -d .svn ]; then
 	REVISION="svn$( svn info | egrep '^Revision:' | cut -f2 -d' ')"
 	SNAPSHOT="-snapshot"
+elif [ -d .bzr ]; then
+	REVISION="bzr$( bzr version-info | egrep '^revno:' | cut -f2 -d' ')"
+	SNAPSHOT="-snapshot"
+else
+	echo 'Revision could not be determined (RELEASE or .svn or .bzr)' >2
+	exit 1
 fi
 _REVISION="-$REVISION"
 echo $REVISION > REVISION
